version: '3.0'
services:
  manager-php-cli:
    build:
      context: ./manager/docker/development
      dockerfile: php-cli.docker
    volumes:
      - ./manager:/app
  manager-php-fpm:
    build:
      context: ./manager/docker/development
      dockerfile: php-fpm.docker
    volumes:
      - ./manager:/app
  manager-nginx:
    build: 
      context: ./manager/docker/development
      dockerfile: nginx.docker
    volumes:
      - ./manager:/app
    ports:
      - 8080:80
    depends_on:
      - manager-php-fpm
  manager-postgres:
    image: postgres:14.2-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
  manager-node:
    build:
      context: ./manager/docker/development
      dockerfile: node.docker
    volumes:
      - ./manager:/app
  manager-node-watch:
    build:
      context: ./manager/docker/development
      dockerfile: node.docker
    volumes:
      - ./manager:/app
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"
  manager-redis:
    image: redis:3.2-alpine
    volumes:
      - redis:/data
    command: redis-server --requirepass secret
  mailer:
    image: mailhog/mailhog:latest
    ports:
      - 8081:8025

volumes:
  pgdata:
  redis: