version: '3.0'
services:
  manager-php-cli:
    image: ${REGISTRY}/manager-php-cli:${TAG}
  manager-php-fpm:
    image: ${REGISTRY}/manager-php-fpm:${TAG}
    restart: always
  nginx:
    image: ${REGISTRY}/manager-nginx:${TAG}
    ports:
      - 80:80
    depends_on:
      - manager-php-fpm
    restart: always
  manager-postgres:
    image: postgres:14.2-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
  mailer:
    image: mailhog/mailhog:latest
    ports:
      - 8081:8025
volumes:
  pgdata: