version: '3.0'
services:
  manager-php-cli:
    image: ${REGISTRY}/manager-php-cli:${TAG}
    depends_on:
      - manager-redis
      - manager-postgres
  manager-php-fpm:
    image: ${REGISTRY}/manager-php-fpm:${TAG}
    restart: always
    depends_on:
      - manager-redis
      - manager-postgres
  nginx:
    image: ${REGISTRY}/manager-nginx:${TAG}
    ports:
      - 80:80
    depends_on:
      - manager-php-fpm
    restart: always
  manager-postgres:
    image: postgres:14.2-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
  manager-redis:
    image: redis:3.2-alpine
    volumes:
      - redis:/data
    command: redis-server --requirepass ${REDIS_SECRET}
  mailer:
    image: mailhog/mailhog:latest
    ports:
      - 8081:8025
volumes:
  pgdata:
  redis: